### ISSUE TITLE
Weapon Modifiers

### ISSUE THREAD

**Issue by Glitch106** [GTLugo/ExtraGunGear#4]
First, I wanna say I'm a big fan of your mod, but for now I can's use it because of a small bug.

So basically, I can reforge my guns to get any modifier, but after I shoot the weapon once, the modifier is removed.

Note: I do have other mods enabled, but disabling this one resolved the modifier bug.  This bug also happens to vanilla weapons.
![Untitled1](https://user-images.githubusercontent.com/51467086/59076416-ec7a5e00-88a3-11e9-8e77-aa6c9d7a893a.jpg)
![Untitled](https://user-images.githubusercontent.com/51467086/59076420-ed12f480-88a3-11e9-8160-34d7698de5d7.png)
![Untitled2](https://user-images.githubusercontent.com/51467086/59076422-ee442180-88a3-11e9-9c9e-3d54a436a0e0.jpg)

**Comment by GTLugo** [comment]
What version are you playing on?  This bug should be fixed in the latest release.

**Comment by Glitch106** [comment]
v1.2.0.0 on tmod loader.

**Comment by Glitch106** [comment]
Oh I see.  I updated it, and now it's fixed.  Thank you.
