### ISSUE TITLE
It's been 2 years...

### ISSUE THREAD

**Issue by Benzilla36** [GTLugo/ExtraGunGear#8]
I just saw the text for the need to update the wiki.. and it was posted 2 years ago. I know you've been working on the rangers arsenal mod, but I feel it shouldn't take this long. sorry if this is bothering you, but please update this, i just got the mod and i'm lost in all of the items, and I don't have a relliable wiki.

**Comment by GTLugo** [comment]
I apologize for causing any frustration, but this is NOT what I do full time. I am a fulltime university student, and this was just something I did for fun a while ago. I put it on pause when they announced tModloader 1.4 would be changing how things are done, which meant I shouldn't keep going until things calmed down. I really detest people doing what you just did and demanding updates when this is not something I get paid for nor is it something I have much time for. That being said, I have been thinking about tinkering with the alpha release of tModloader 1.4, but no promises.

**Comment by Benzilla36** [comment]
Sorry i bothered you, but thank you for acknowleding me, I hope it's okay with you, but when i figure out more things about the mod, I hope it's all right if I help with the wiki. Thank you.
